name: Testing workflow

on: [push, pull_request]

jobs:
  style check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install style checker"
        run: pip install --user black
      - name: "Run style check"
        run: black --check .
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install pytest dependency"
        run: pip install --user  pytest
      - name: "Run unittest"
        run: python -m unittest
  coverage report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install coverage dependency"
        run: pip install --user  coverage
      - name: "Run coverage"
        run: coverage run -m pytest
    
#  build:
#    needs: style
#    runs-on: ubuntu-latest
#    env:
#      PROJECT_NAME: "Automation Lecture"
#    steps:
#      - name: "Run build phase"
#        run: echo "Building project $PROJECT_NAME"
  